### ISSUE TITLE
Python3: installation fails on non-English locales

### ISSUE THREAD

**Issue by yegorich** [svinota/pyroute2#169]
README.md is encoded in UTF-8, i.e. has characters with value more than 128. This causes following errors, when setup.py tries to read README.md in Python3:

http://lists.busybox.net/pipermail/buildroot/2015-August/137126.html

Could you either make README.md file ASCII only or handle UTF-8 files properly?

To reproduce the issue just invoke:
export LANG=de_DE
and then try to read this file in Python3.

**Comment by svinota** [comment]
Ough, pardonnez-moi. Will fix it immediately.

**Comment by svinota** [comment]
Unfortunately, I can not reproduce it on my systems with any locale settings, so I just removed unicode characters from README.md in a hope it will be enough. But since I can not reproduce the failure, I can not check it.

So pls take a look, if it will work. If not, ping me. Thanks a lot for the report.

**Comment by svinota** [comment]
Pls tell also, if the master HEAD is not enough and a new pypi release is required (I see the packaging issue in the reference you gave, and sometimes it matters for packaging procedures)

**Comment by yegorich** [comment]
@svinota thanks for the fix. I was waiting for some additional tests and it seems like the issue is solved. Release would be great, but it can wait. This package was applied to Buildroot repository and I'll update it as soon as you make a new release.

**Comment by svinota** [comment]
Ok, great! Thanks
