### ISSUE TITLE
Support controlling STP states

### ISSUE THREAD

**Issue by evanfoster** [svinota/pyroute2#201]
It would be awesome to be able to control STP states like the bridge utility is able to if it isn't already possible. There's currently no easy way to control STP in Python as far as I can see.

I would love to be able to do the equivalent of this command: 
`bridge link set dev eth0 state 4`

EDIT:

In ifinfmsg.py, I found `IFLA_BRIDGE_STP_STATE` but running this command:
`ip.link("set", index=1, IFLA_BRIDGE_STP_STATE=4`
Gives this output:
`[{'header': {'pid': 21217, 'length': 36, 'flags': 0, 'error': None, 'type': 2, 'sequence_number': 288}, 'event': 'NLMSG_ERROR'}]`

**Comment by svinota** [comment]
The issue is that the netlink protocol doesn't allow the STP state management. At least in kernels prior to 4.x, but I believe that in 4.x as well. So we have to use the sysfs to do so. The sysfs code for bridges and bonds is integrated and is working, but is a bit tricky to access.

As a proof-of-concept I made a shortcut in the `IPLinkRequest` class:
```
from pyroute2 import IPRoute
from pyroute2 import IPLinkRequest

ip = IPRoute()
idx = ip.link_lookup(ifname='br0')[0]
ip.link('set', **IPLinkRequest({'index': idx,
                                'kind': 'bridge',
                                'stp_state': 1}))
ip.close()
```

The `IPLinkRequest` is a helper class that allows to simplify the NLA construction, which can be very complicated in some cases. You can play around and print `IPLinkRequest` objects for different cases to see, what is the result. It's not my caprice, it's the NLA structure that should be passed to the kernel.

Notes:
1. the `kind` reference is required to correctly handle the `stp_state`.
2. the `IPLinkRequest` should be passed with `**`, as a keyword args dictionary.

…

The `NLMSG_ERROR` response is normal — the kernel returns it for some requests. Most important that `error` is `None`. If it is not `None`, the library throws an exception, so you will not miss an error.

**Comment by svinota** [comment]
Please notice, it is not the final implementation of the STP support, though this syntax will work anyway. If you have ideas, how to make the syntax simpler, don't hesitate to propose.

**Comment by evanfoster** [comment]
Ah, fantastic! Thank you so much. I'll see if I can think of some ways to make the syntax a bit easier to grok, although I'm still a relatively new programmer and most of the code I write is ugly as sin.

**Comment by svinota** [comment]
I do not close the issue, since it has to be documented in the next release.

**Comment by svinota** [comment]
Docs added, closing the issue.

**Comment by evanfoster** [comment]
Awesome, thanks for being so responsive and for making such a great library! pyroute2 really saved my butt.

**Comment by svinota** [comment]
Ye're welcome :) Thanks!
