### ISSUE TITLE
Add examples into released tarball

### ISSUE THREAD

**Issue by vincentbernat** [svinota/pyroute2#226]
Hi!

The tarball on Pypi doesn't include examples. It would be convenient to have them. It should just be a matter of adding the directory to `MANIFEST.in`.

**Comment by svinota** [comment]
Thanks, done. Examples will be provided with the next release.

**Comment by haizeiwang507** [comment]
@svinota 
      Hello!  Recently, I am building a " netlink " for embedded linux (used in Openwrt Wireless Router, the language is C ). Firstly,I must cross compile netlink on Openwrt with user mode and kernel mode. 
the problem is that can't successfully cross compiled in kernel mode (user mode is okay), can you help me .
the cross compile Makefile is : 

# Kernel module example
include $(TOPDIR)/rules.mk
include $(INCLUDE_DIR)/kernel.mk

PKG_NAME:=example
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define KernelPackage/example
  SUBMENU:=Other modules
  DEPENDS:=@!LINUX_3_3
  TITLE:=Support Module for example
  FILES:=$(PKG_BUILD_DIR)/example/example.$(LINUX_KMOD_SUFFIX)
  AUTOLOAD:=$(call AutoLoad,81,example)
  KCONFIG:=
endef

MAKE_OPTS:= \
	ARCH="$(LINUX_KARCH)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	SUBDIRS="$(PKG_BUILD_DIR)"
	
define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
endef

define Build/Compile
　　$(MAKE) -C "$(LINUX_DIR)" \
		$(MAKE_OPTS) \
		modules
endef
$(eval $(call KernelPackage,example))





the install Makefile: 
obj-m +:= netopk.o 

the Kconfig;
config 	NETOPK
　　tristate "Just a netopk"
　　default n
　　help
　　　This is a netopk, for debugging kernel model.
　　　If unsure, say N.





and netopk (netlink);

#include <linux/init.h>
#include <linux/module.h>
#include <linux/timer.h>
#include <linux/time.h>
#include <linux/types.h>
#include <net/sock.h>
#include <net/netlink.h>
#include <linux/string.h>

#define NETLINK_TEST 25
#define MAX_MSGSIZE 1024

struct sock *nl_sk = NULL;

void send_msg(char *message, int pid)
{
	struct sk_buff *skb;
	struct nlmsghdr *nlh;
	int len = NLMSG_SPACE(MAX_MSGSIZE);

	if (!message || !nl_sk) {
	         return;
	}
	printk(KERN_INFO "pid:%d\n", pid);
	skb = alloc_skb(len, GFP_KERNEL);
	if (!skb) {
	         printk(KERN_ERR "send_msg:alloc_skb error\n");
	        return;
	}
	nlh = nlmsg_put(skb, 0, 0, 0, MAX_MSGSIZE, 0);
	NETLINK_CB(skb).portid = 0;
	NETLINK_CB(skb).dst_group = 0;
	strcpy(NLMSG_DATA(nlh), message);
	printk(KERN_INFO "my_net_link:send message '%s'.\n",(char *)NLMSG_DATA(nlh));
	netlink_unicast(nl_sk, skb, pid, MSG_DONTWAIT);
	}

void recv_nlmsg(struct sk_buff *skb)
	{
	int pid;
	struct nlmsghdr *nlh = nlmsg_hdr(skb);

	if (nlh->nlmsg_len < NLMSG_HDRLEN || skb->len < nlh->nlmsg_len)
	        return;

	printk(KERN_INFO "Message received:%s\n", (char*)NLMSG_DATA(nlh));
	pid = nlh->nlmsg_pid;
	send_msg("I am from kernel!", pid);
	}

struct netlink_kernel_cfg nl_kernel_cfg = {
	.groups = 0,
	.flags = 0,
	.input = recv_nlmsg,
	.cb_mutex = NULL,
	.bind = NULL,
	.compare = NULL,
	};

int netlink_init(void)
	{
	nl_sk = netlink_kernel_create(&init_net, NETLINK_TEST, &nl_kernel_cfg);
	if (!nl_sk) {
	         printk(KERN_ERR "my_net_link: create netlink socket error.\n");
	         return 1;
	}
	printk(KERN_INFO "netlink_init: create netlink socket ok.\n");
	 return 0;
	}

static void netlink_exit(void)
	{
	if (nl_sk != NULL)
	        sock_release(nl_sk->sk_socket);

	printk(KERN_INFO "my_net_link: self module exited\n");
	}

module_init(netlink_init);
module_exit(netlink_exit);
MODULE_AUTHOR("vv1133");
MODULE_LICENSE("GPL");

my purpose is just   we can Send and receive  messages to/from each other. can you help me ? thank you ! (my router is netgear wndr4300,linux kernel version is 3.10.49)

**Comment by svinota** [comment]
@haizeiwang507 with all the respect, I believe that the issue record is not an appropriate place to discuss such questions. I'm sorry, I will not help here with it and within a day the comment will be wiped out.

**Comment by haizeiwang507** [comment]
@svinota 
I am so sorry , it is first time for me to touch "netlink" , I just want to  know which  dependency packages are needed  for  "netlink",  it always show error:
bash: $'\343\200\200\343\200\200make': command not found

**Comment by svinota** [comment]
@haizeiwang507 you have a typo in the command line, it has nothing to do with dependencies. I'm removing the comments.
