### ISSUE TITLE
IPDB Instance Failure (0.4.1)

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#258]
### Observation
After using the `IPRoute` instance to setup networking as my application needs, I then attempt to use `IPDB` to monitor for changes that I must react to.  When starting my instance, I'm getting a repeated failure:

```
2016-05-31 09:07:21 - pyroute2.ipdb.main - ERROR - Restarting IPDB instance after error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 1052, in serve_forever
    messages = self.mnl.get()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 695, in get
    msgs = self.marshal.parse(data)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 153, in parse
    (length, msg_type) = struct.unpack_from('IH', data, offset)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
```

This failure continues at a frequency of 2-4 incidents per second.  When this occurred, my kernel also hit an OOM condition in the 3rd second of operation of my daemon to which my daemon is to blame.  I suspect that the above failure is significantly contributing to the memory exhaustion.

### Setup
- **pyroute2:** 0.4.1

    *For the time being, I've rolled back to 0.3.22 without issue*

- **Kernel:** 3.14.0-rc2
  - [IMQ patch](http://www.linuximq.net/)
  - [AuFS patch](http://aufs.sourceforge.net/)

### Other Info
If any additional information would be helpful to complete RCA on this issue, please feel free to reach out.

**Comment by svinota** [comment]
Ough. Thanks a lot. Investigating.

**Comment by svinota** [comment]
Could you please tell also the Python version?

**Comment by tomislacker** [comment]
#### Python Version

```sh
$ python -V
Python 2.7.3
```

#### Other Global Dependencies

```sh
$ pip freeze
PyYAML==3.11
argparse==1.2.1
distribute==0.6.24dev-r0
dnspython==1.14.0
docopt==0.6.2
iotop==0.4.4
mosquitto==0.15
netaddr==0.7.18
pyaml==15.8.2
pyroute2==0.3.22
python-augeas==0.5.0
python-iptables==0.11.0
sh==1.11
terminaltables==3.0.0
wsgiref==0.1.2
```

**Comment by svinota** [comment]
No, I do not understand... Look:

```python
(length, msg_type) = struct.unpack_from('IH', data, offset)
TypeError: unpack_from() argument 1 must be string or read-only buffer, not bytearray
```

`argument 1`. But in the backtrace argument 1 is a string: 'IH'. The bytearray is argument 2. That's meaningless. Are you sure that no monkeypatches are applied to the struct module, or `struct.unpack_from()`?

**Comment by tomislacker** [comment]
@svinota I'm certain.  Besides the crazy application logic that's doing the rearranging of routing rules & tables, this application is quite simple.

**Comment by svinota** [comment]
Could you please try the following:

* run the python cli and instantiate IPDB:
```
from pyroute2 import IPDB
IPDB().release()
```
* in the python cli try that code:
```
import struct
struct.unpack_from('I', bytearray((1,0,0,0)), 0)
```

Thanks for your patience. The case is really strange.

**Comment by tomislacker** [comment]
It'll probably be about 18-20hrs before I can setup this test & get back to you.  Appreciate your time as always sir.

**Comment by svinota** [comment]
That's my mistake, I had to recognize the issue from the beginning :| My apologies.

No need to set up it, the issue is clear now. Actually, there are several issues at once.

1. The `bytearray` class changed it's API in some of early Python 2.7 versions, so now it supports the buffer protocol, and that's the cause of the backtrace on 2.7.3. But not the root cause. I didn't look exactly in which version the change took place, since…
2. The 0.4.x versions of the pyroute2 library do not support transparent bridge/bond management on old kernels. I stopped the CI testing of 0.4.x on RHEL6.5, thus ignoring not only the old kernel version, but the old Python version too.

The old kernels do not provide the netlink RTNL API to bridges and bonds, so they were managed there by pyroute2 via external utilities (while on the new kernels pyroute2 used RTNL only). But the proxy code, that managed these external utilities, became one of the performance bottlenecks, so I completely dropped it starting with 0.4.0.

Another bottleneck (and a memory consumption issue) was the buffer copying, so now the library uses `recv_into()` and `unpack_from()` to save the memory and to copy no extra buffers. But that makes it incompatible with old Python versions.

Thus, there are two branches of the library now, 0.3.x (LTS for platforms like RHEL, but w/o new features like rules management in IPDB) and 0.4.x (w/o compat code, fast and memory-efficient, but incompatible with old platforms)

And while I don't care about 0.4.x on old kernels, it still must work on (reasonably) old Python versions. I will try to find an acceptable workaround, if there is no way for you to use a newer Python version. And even then be aware that 0.4.x will not manage bridges and bonds on the kernel 3.14.

Thanks for such serious issue. Again, I had to find it by myself. I'm sorry.

**Comment by svinota** [comment]
Action: 0.4.x to log at least warning if started on old kernels?

**Comment by svinota** [comment]
Look, now the 0.4.x should start on old Python versions too. But it will not provide the bridge management (since the kernel doesn't provide it via RTNL).

**Comment by tomislacker** [comment]
Looks good, thank you much.

**Comment by svinota** [comment]
Thanks for you patience and for the feedback!

**Comment by svinota** [comment]
An additional fix for RHEL6.5 / Python 2.6
