### ISSUE TITLE
Hangs/dst not set when trying to add a ipv6 route

### ISSUE THREAD

**Issue by vodik** [svinota/pyroute2#307]
I have the following snippet:

``` python
import pyroute2


def add_route(dst, gateway):
    route_key = {'dst': dst, 'gateway': gateway}

    with pyroute2.IPDB() as ipdb:
        print("Add route...")
        ipdb.routes.add(route_key).commit()
        assert ipdb.routes[route_key]


add_route('fd00:6d:3d1a::1/64', '2001:4c8:1023:108::40')
add_route('172.31.0.0/24', '10.10.8.40')
```

Works for any ipv4 addresses I set, but hangs with ipv6 with the transactional stuff eventually complaining that "target dst is not set".

I spend some time looking under the hood, and as far as I can tell, the routes stuff is picking up the new route from netlinks, parsing it properly, and doing set item for the "dst" key correctly.

**Comment by vodik** [comment]
Okay, I think I've narrowed down the problem. The field is not being unlocked in `__setitem__` inside transactional.py, because `global_tx` is not getting updated when a new ipv6 address comes in, where as it does for ipv4.

Might be able to figure this out after all...

**Comment by svinota** [comment]
Thanks! Fixing

**Comment by svinota** [comment]
The issue is located, I'm trying to fix it. Expect the fix to be delivered on Sunday. Thanks for the patience.

**Comment by vodik** [comment]
Well looking forward to see where the problem was. I spent a lot of time trying to root through all the transnational logic and couldn't find it.

**Comment by svinota** [comment]
@vodik — the problem is not in the transaction logic.

The IPDB uses «keys» to identify routes, and these keys are built from `dst` and `priority` fields (there may be several routes for the same destination, but with different priorities). The `priority` is the proper kernel name for what is called `metric` in iproute utility.

By default, the `priority` is None, unless explicitly specified. And with IPv4 routes it work ok. But if the priority not specified for an IPv6 route, the kernel forces it. And thus IPDB can not locate the proper route in the DB, since it created a route w/o priority, but from the kernel comes a route with a specific priority.

So I'm to change the route key semantics in the IPDB for IPv6 routes, thanks to your report.

**Comment by svinota** [comment]
Pls try the master. But notice please, that the route should be specified as a network, not as a host:

add_route('fd00:6d:3d1a::~~1~~/64', '2001:4c8:1023:108::40')
→ add_route('fd00:6d:3d1a::/64', '2001:4c8:1023:108::40')

**Comment by vodik** [comment]
Thanks! Giving it a shot.

And yeah, oops. I'm aware its not valid, Typo'd as I tried to simplify what we where seeing in production.

**Comment by vodik** [comment]
:+1: works for me.
