### ISSUE TITLE
Setting bridge-related properties for a port

### ISSUE THREAD

**Issue by vincentbernat** [svinota/pyroute2#364]
Hey!

I am trying to set some bridge-related properties on an enslaved port. For example, I would like to do something similar to `bridge link set dev eth6 flood off`. The `bridge` utility create a `IFLA_PROTINFO` attribute and put `IFLA_BRPORT_UNICAST_FLOOD` attribute in it. I have tried to do the same thing without success.

```
            ip.link("set",
                    family=socket.AF_BRIDGE,
                    index=link['index'],
                    brport_unicast_flood=0)
```

```
            ip.link("set",
                    family=socket.AF_BRIDGE,
                    index=link['index'],
                    IFLA_PROTINFO={'attrs': [['IFLA_BRPORT_UNICAST_FLOOD',
                                              0]]})
```

```
            ip.link("set",
                    family=socket.AF_BRIDGE,
                    index=link['index'],
                    IFLA_LINKINFO={'attrs':
                                   [['IFLA_INFO_SLAVE_DATA',
                                     {'attrs': [['IFLA_BRPORT_UNICAST_FLOOD',
                                                 0]]}]]})
```

The last one is because this is what I get when using `ip.get_links`.

I also tried:

```
            ip.link("set",
                    family=socket.AF_BRIDGE,
                    index=link['index'],
                    IFLA_LINKINFO={'attrs':
                                   [('IFLA_INFO_SLAVE_KIND', 'bridge'),
                                    ('IFLA_INFO_SLAVE_DATA',
                                     {'attrs': [('IFLA_BRPORT_UNICAST_FLOOD',
                                                 0)]})]})
```

**Comment by svinota** [comment]
I'll try tonight

**Comment by vincentbernat** [comment]
A better starting point would be:

```
            ip.link("set",
                    family=socket.AF_BRIDGE,
                    index=link['index'],
                    protinfo={'attrs': [('IFLA_BRPORT_UNICAST_FLOOD', 0)]})
```

This time, I get an invalid argument error.

At the end of `encode_nlas`, I get: `[['IFLA_INDEX', 0], ('IFLA_PROTINFO', {'header': {'length': 12, 'type': 12}, 'attrs': [('IFLA_BRPORT_UNICAST_FLOOD', 0)], 'value': <class 'pyroute2.netlink.NotInitialized'>})]`.

**Comment by svinota** [comment]
Found the cause — beside of the NLA per se it is required to specify NLA flags here, and API doesn't provide yet the way to do that.

But I fix that tomorrow.

**Comment by svinota** [comment]
Please check out the `brport` branch, if it will work for you.

It's a draft, the documentation and tests will be provided tonight.

An example:
```python
with IPRoute() as ipr:
    ipr.brport('set', index=link['index'], unicast_flood=0, cost=200, proxyarp=1)
    print(ipr.brport('show', index=link['index']))
```

**Comment by vincentbernat** [comment]
It works just fine for me, thanks!

**Comment by svinota** [comment]
So I add the docs and merge into the master tomorrow.

**Comment by svinota** [comment]
Merged into the master. Closing as «resolved», but feel free to re-open the ticket in case of issues.

**Comment by svinota** [comment]
JFYI: added the feature to the IPDB code:
```python
with IPDB() as ipdb:
    with ipdb.interfaces[link['index']] as i:
        i.unicast_flood = 0
        i.cost = 200
        i.proxyarp = 1
```

**Comment by vincentbernat** [comment]
Unrelated to the issue, but I was relunctant to use ipdb because "too much magic". I am notably worried by the automatic rollback that could happen during an error. Does the entire configuration is rollbacked or only the modifications that have been applied? For example, suppose that before commiting a change, an unrelated interface is modified by a program (an IP address is added to it for example). Is there a risk that the change is cancelled if my own change fails for some reason?

I think this would be worth explaining in the documentation the scope of ipdb "apply/commit". I can do a PR with that once I understand more how it works.

**Comment by svinota** [comment]
> because "too much magic"

I agree :) It was started as a proof-of-concept, but people use it, so I try to keep it as stable as it is possible. And as the time passes, there is some empiric accumulated about different kernel flavours and their behaviour — the RTNL API in the kernel is quite messy. I can not put much of this empiric into the `IPRoute` interface, since it's supposed to be more or less a pure RTNL reflection. But it stays in the `commit()` call in IPDB plugins.

> Does the entire configuration is rollbacked or only the modifications that have been applied?

The algo is as follows:
1. on the first interface change, IPDB makes a «linked snapshot» of the interface, that keeps all the changes made from this IPDB, but also reflects «3rd party» changes — IPDB listens for RTNL updates continuously.
2. on `commit()`, the interface IPDB plugin (route and rule plugins behave a bit different) makes two additional «interface» objects:
```python
removed, added = snapshot // transaction
# roughly, it's equal to:
added = transaction - snapshot
removed = snapshot - transaction
```
3. upon failure, IPDB runs `commit()` with `spanshot` as the transaction. It must **revert only those changes, that are made by the failed `commit()`**. But since RTNL has no locking, theoretically there may be some races.

Thus,
> suppose that before commiting a change, an unrelated interface is modified by a program (an IP address is added to it for example). Is there a risk that the change is cancelled if my own change fails for some reason?

No, should not be. If it happens, it is a bug and should be fixed. By design IPDB is supposed to run as a **non**-exclusive settings DB, synced with the real system state, whatever can change it at any time.

That's why there is still no support for the traffic controls in the IPDB — there is no changes broadcasting in the kernel TC subsystem. But interfaces, addresses, neighbours, routes and rules are synced just fine.
