### ISSUE TITLE
IPDB route delete issue

### ISSUE THREAD

**Issue by pugna0** [svinota/pyroute2#421]
Env: os  Fedora-26
       python 2.7
First, I use shell to add route:
ip route add 10.10.10.0/24 table 20 nexthop via 10.6.5.114 dev eno1 weight 1 nexthop via 10.6.5.114 dev eno1 weight 1 nexthop via 10.6.5.114 dev eno1 weight 1

ip route show table 20
output:
  10.10.10.0/24 
    nexthop via 10.6.5.114 dev eno1 weight 1 
    nexthop via 10.6.5.114 dev eno1 weight 1 
    nexthop via 10.6.5.114 dev eno1 weight 1
now I try to delete all prefix matched in table 20:
with ip.routes.tables[table][prefix] as r:
          # this two method both trigger the same error
            result = r.remove()
                         or
            r.del_nh({'gateway': nexthop})
output:
  Traceback (most recent call last):
  File "a.py", line 68, in <module>
    print route_del("10.10.10.0/24", 20)
  File "a.py", line 14, in func_wrapper
    return func(*args, **kwarg)
  File "a.py", line 52, in route_del
    return True, result
  File "/home/pugna/virtual_env/yabgp/lib/python2.7/site-packages/pyroute2/ipdb/transactional.py", line 209, in __exit__
    self.commit()
  File "/home/pugna/virtual_env/yabgp/lib/python2.7/site-packages/pyroute2/ipdb/routes.py", line 483, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (3, 'No such process')

then I add a mulipath nexthop with pyroute2 api:
 ip.routes.add(dst="10.6.5.115", table=table, multipath=multipath).commit()   

ip route show table 20
output:
  10.10.10.0/24 
    nexthop via 10.6.5.114 dev eno1 weight 1 
    nexthop via 10.6.5.115 dev eno1 weight 1 

It is strange...
But, route delete method could run well.
            result = r.remove()
            r.del_nh({'gateway': nexthop})

**Comment by svinota** [comment]
Is it the master HEAD or one of the releases?

**Comment by pugna0** [comment]
release 0.4.17, installed from pip

**Comment by svinota** [comment]
Looks like an issue with route keys. Could you please try to upgrade to 0.4.21 from pip?

**Comment by PaulSD** [comment]
This works for me using current master.

**Comment by pugna0** [comment]
It seems that pyroute2 (0.4.21) still has above problem, besides, after adding three same multipath route:
root@localhost:~ $ip route show table 21
10.10.10.0/24 
	nexthop via 10.6.5.114 dev eno1 weight 1 
	nexthop via 10.6.5.114 dev eno1 weight 1 
	nexthop via 10.6.5.114 dev eno1 weight 1

remove() method will raise  pyroute2.netlink.exceptions.NetlinkError: (3, 'No such process')
del_nh({'gateway': nexthop}) raise: pyroute2.netlink.exceptions.NetlinkError: (19, 'No such device')

**Comment by svinota** [comment]
Ok, thanks! Fixing.

**Comment by svinota** [comment]
@pugna0 no, not fixing. The issue is that in IPDB multipath hops are stored with a unique index on `(gateway, encap, oif)`. It is possible to change the DB arch, but it takes too much effort, as it is a custom object-oriented DB.

If the issue with multiple same hops on a multipath route is critical to you, or you believe it may be critical, pls let me know, I'll try to fix.

Otherwise I'm focused on an IPDB replacement — https://github.com/svinota/pyroute2/blob/master/pyroute2/ndb/main.py

Some initial docs & samples will be available on 0.5.2. The NDB module uses a completely different approach than IPDB (e.g., it employs an in-memory SQL DB) and I believe this issue will not be relevant just because of the DB schema.
