### ISSUE TITLE
Unable to get whole v4 and v6 routes at once.

### ISSUE THREAD

**Issue by RiccardoManfrin** [svinota/pyroute2#451]
```
>>> [x.get_attr('RTA_DST') for x in ip.get_routes(family=socket.AF_INET)]
['10.120.0.0']
>>> [x.get_attr('RTA_DST') for x in ip.get_routes(family=socket.AF_INET6)]
[None, 'fe81::']
>>> [x.get_attr('RTA_DST') for x in ip.get_routes()]
['10.120.0.0']
```

Reading from doc here http://docs.pyroute2.org/iproute.html 
```
Example:

ip.get_routes()  # get all the routes for all families
ip.get_routes(family=AF_INET6)  # get only IPv6 routes
ip.get_routes(table=254)  # get routes from 254 table
```
I would expect the 3rd call (without parameters) to return the union of the former two.

**Comment by svinota** [comment]
Investigated a bit on that. The issue is that the kernel should return all the routes in response to `family=AF_UNSPEC`, but instead it returns only IPv4 ones. Moreover, any wrong `family` value forces the kernel to return all the routes! Try `family=AF_UNIX`, e.g.

I will reflect that in the docs, but I would prefer to make no «smart» solutions in that case as the `IPRoute` module is still a 1-to-1 RTNL mapping, so the kernel's issues must be reflected as well.

**Comment by svinota** [comment]
Added to the docs.
