### ISSUE TITLE
NDB module, issue creating veth interfaces

### ISSUE THREAD

**Issue by fernandoroyosanchez** [svinota/pyroute2#607]
Hi, 

I'm having several problems using NDB on creation of 'veth' interfaces. For bridge ones it works like a charm.

Basically the scope to reproduce the issue is this config:

* pyroute2 0.5.5 (stable)
* Init instance of NDB to localhost namespace
* Create bridge and up - OK
* Create bridge and up - OK
* Create veth iface  - Sometimes Timeout problem! and other 

```
from pyroute2 import NDB, IPRoute
ndb=NDB(sources={'localhost':IPRoute()})
ndb.interfaces.add(ifname='br_if', target='localhost', kind='bridge',state='up').commit()
ndb.interfaces.add(ifname='veth0', target='localhost', kind='veth', peer='veth0_1', state='down').commit()
```

The last command sometimes return Timeout, some other times 
pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')

any comment or issue working with veth using NDB??

**Comment by svinota** [comment]
Thanks for the issue, it's to be fixed tonight.

I prepare a release this weekend with a lot of fixes to the NDB module (>130 commits out of almost 200 since 0.5.5 touch NDB), it's quite new, thus so many changes. But I hope to completely obsolete IPDB module in two-three releases, so working hard to get NDB in place.

NB: the method becomes renamed, `add()` → `create()` to avoid confusion with port management functionality.

**Comment by svinota** [comment]
Should be fixed now, please check. Documentation will follow these days.
