### ISSUE TITLE
Error when setting wireguard peers

### ISSUE THREAD

**Issue by nickhuber** [svinota/pyroute2#642]
Following the instructions on the wireguard file, I get the following exception when trying to call wg.set() to add a peer.

```
Traceback (most recent call last):
  File "../bonding/wg-test.py", line 19, in <module>
    fwmark=0x1337, listen_port=2525, peer=peer)
  File "/usr/local/lib/python3.7/site-packages/pyroute2/netlink/generic/wireguard.py", line 295, in set
    raise err
pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')
```

I tried running the example from https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/generic/wireguard.py verbatim, and still got the same error.

**Comment by Vic063** [comment]
Hi @nickhuber,

it looks like the WireGuard netlink API structure was recently modified, I will look into that today.

**Comment by svinota** [comment]
@Vic063 thanks a lot

**Comment by Vic063** [comment]
@svinota,
it seems to be impacted since this commit in WireGuard: 3120425f69003be287cb2d308f89c7a6a03
I still have not found a correct way to handle strict NLA length types in pyroute2.

@nickhuber: to be sure, you are doing your tests using a kernel version >= 4..20?

**Comment by svinota** [comment]
@Vic063 I'll try to look into the wireguard code.

If you tell me more about the requirements to the types, probably I could help somehow. Here or we can set up a Google Hangouts session.

**Comment by nickhuber** [comment]
@Vic063 I am testing on a recent Fedora 30 kernel, 5.2.18-200.fc30.x86_64

**Comment by Vic063** [comment]
> @Vic063 I'll try to look into the wireguard code.
> 
> If you tell me more about the requirements to the types, probably I could help somehow. Here or we can set up a Google Hangouts session.

Since WireGuard added .type 'NLA_MIN_LEN' attribute in the 'WGPEER_A_ENDPOINT' declaration (and some others), it adds this sequences of bytes in the netlink payload:
0800030002000000

Before kernel 4.20, the payload for 'WGPEER_A_ENDPOINT' was the following:
1400: size
0400: type
0200: family (AF_INET)
22b8: endpoint port (8888)
08080808: ipv4 endpoint (8.8.8.8)
00000000: ipv6 endpoint
00000000: padding

Now the payload is:
1400: size
0400: type
0200: family (AF_INET)
22b8: endpoint port (8888)
08080808: ipv4 endpoint (8.8.8.8)
00000000: ipv6 endpoint
00000000: padding
0800: length
0300: type
02000000: data (2)

I don't know if these informations can help you.

**Comment by svinota** [comment]
@Vic063 

If I do undestand correctly what I see here, it's just two NLAs one after another:
```
  length = 0x14
  type = 0x4
  data = [...]
```
and 
```
   length = 0x8
   type = 0x3
   data = [...]
```

The type 0x3 is `WGPEER_A_FLAGS`, iirc.

Let me see if I can debug it tomorrow.

**Comment by Vic063** [comment]
Should be fixed with #652

**Comment by ffourcot** [comment]
@nickhuber Do you have any feedback on #653 ?

**Comment by svinota** [comment]
Added basic tests to include WireGuard in the CI loop.
