### ISSUE TITLE
`target dst is not set` test failure

### ISSUE THREAD

**Issue by smurfix** [svinota/pyroute2#766]
The test `tests/general/test_examples.py::TestExamples::test_ipdb_routes` fails on my system with the above error.
```
tests/general/test_examples.py::TestExamples::test_ipdb_routes client error:
target dst is not set
server error:
None
```

Removing the (IMHO stupid) error aggregation resulted in a traceback:
```
[…]
/src/aevent/sample/pyroute2/examples/ipdb_routes.py:16: in <module>
    pass
/src/aevent/sample/pyroute2/pyroute2/ipdb/transactional.py:210: in __exit__
    self.commit()
/src/aevent/sample/pyroute2/pyroute2/ipdb/routes.py:572: in commit
    raise error
/src/aevent/sample/pyroute2/pyroute2/ipdb/routes.py:519: in commit
    transaction.wait_all_targets()
/src/aevent/sample/pyroute2/pyroute2/ipdb/transactional.py:523: in wait_all_targets
    raise CommitException('target %s is not set' % key)
E   pyroute2.ipdb.exceptions.CommitException: target dst is not set
```

Adding some debug statements showed that the `Route` instance which `BaseRoute.load_netlink` uses to read the route in question isn't the same instance as the one `wait_all_targets` is waiting for.

I havent yet figured out why not, as I'm not that familiar with the pyroute2 code base.

**Comment by svinota** [comment]
The reason was the fix https://github.com/svinota/pyroute2/pull/736/commits/d5fa53b47b23262b69cf07fa9eeca3bca4780bed to the issue https://github.com/svinota/pyroute2/pull/736 .

1. rolling back the fix https://github.com/svinota/pyroute2/pull/736/commits/d5fa53b47b23262b69cf07fa9eeca3bca4780bed
2. mentioning https://github.com/svinota/pyroute2/pull/736 in the docs
3. freezing IPDBs changes in that part

That all is caused by IPDB's bad architecture and that's exaclty why IPDB will be decommissioned sooner or later.

Meanwhile preparing a module that would ease IPDB → NDB migration.

**Comment by svinota** [comment]
- [x] raise deprecation warning on IPDB run
- [x] remove IPDB examples
- [x] provide corresponding NDB examples
- [x] cover NDB examples with testing
