### ISSUE TITLE
NDB loses sync: Removing all IPs from an interface also removes the routes which NDB doesn't recognize

### ISSUE THREAD

**Issue by sirkrypt0** [svinota/pyroute2#849]
When removing all IPs from an interface, Linux removes all routes associated with that interfaces. NDB does not recognize this and loses sync when trying to remove one of the previously associated routes.

## Steps to reproduce

```python
import pyroute2
ndb = pyroute2.NDB()
interface = ndb.interfaces.create(ifname='test', kind='bridge')
interface.set('state', 'up').commit()
interface.add_ip('10.0.0.1/32').commit()
ndb.routes.create(dst='10.0.0.2/32', oif=interface['index']).commit()
interface.del_ip('10.0.0.1/32').commit()
ndb.routes['10.0.0.2/32'].remove().commit()
```

Running the above script hangs for a while and finally terminates with `Exception: lost sync in apply()`.

**Comment by svinota** [comment]
The issue is that there are no events from the kernel regarding such route removal, so the only way is to drop related records.

It is relatively simple when we remove all the associated records upon an interface removal, but with an address removal it's a bit tricky — we have to check the ip ranges (and hope there is no race condition in the setup).

But I finally found a way to do that properly, so it'll be ready in days.

Thanks for the report.
