### ISSUE TITLE
PyPy tar ball with integrated docs

### ISSUE THREAD

**Issue by craneworks** [svinota/pyroute2#91]
Hey ho,

we are currently building a package of pyroute2 for Debian.
For this package we are using the tar ball from PyPy. Could you please add the docs into this tar ball? That'd be greate. :)

**Comment by svinota** [comment]
Will be done with 0.3.4 — I will release it earlier.

Thanks a lot!

**Comment by svinota** [comment]
Please check, if it will pass: http://pyroute2.org/pyroute2-0.3.3-53-geca483e.tar.gz

If so, 0.3.4 will be uploaded to pypi with this directory layout.

**Comment by svinota** [comment]
@FedericoCeratto , probably, you can be interested in this as well.

**Comment by craneworks** [comment]
For me this looks fine. I think Federico will also be happy with it. :)

**Comment by svinota** [comment]
So be it, 0.3.4 will be released this weekend with docs in this format.

I keep html docs in a subdir, since later there can be some other docs added as well — like diagrams, plain text files etc.

Pls notice, that setup.py doesn't install the docs (may be to change later?), they are just packed into the tarball.

**Comment by svinota** [comment]
PyPI tarball published, closing the issue.
